# Modern R Development Guide: runnable examples
#
# GENERATED from R-dev-guide.md by check-examples.R. Do not edit this file; edit the
# guide and run:  Rscript check-examples.R --write
#
# Runs top to bottom. The first section creates a temporary project directory and
# writes the guide's project files into it; every later section runs from there.

# ── Example project ─────────────────────────────────────────────────────────────
example_dir <- file.path(tempdir(), "modern-r-dev-examples")
dir.create(example_dir, recursive = TRUE, showWarnings = FALSE)
setwd(example_dir)
invisible(file.create(".here"))

# ── file: R/analysis.R ──────────────────────────────────────────────────────────
dir.create("R", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# R/analysis.R
library(data.table)

compute_effect_size <- function(x, y, type = c("cohen_d", "glass_delta")) {
  if (!is.numeric(x) || !is.numeric(y)) stop("`x` and `y` must be numeric")
  type      <- match.arg(type)
  pooled_sd <- sqrt(((length(x) - 1) * var(x) + (length(y) - 1) * var(y)) /
                    (length(x) + length(y) - 2))
  if (type == "cohen_d") {
    (mean(x) - mean(y)) / pooled_sd
  } else {
    (mean(x) - mean(y)) / sd(y)
  }
}

fit_group_models <- function(dt, formula, group_col) {
  dt_list <- split(dt, by = group_col)
  fits    <- lapply(dt_list, function(d) lm(formula, data = d))
  coefs   <- lapply(fits, function(f) {
    co <- coef(f)
    data.table(term = names(co), estimate = unname(co))
  })
  rbindlist(coefs, idcol = group_col)
}

# Modifies in place: the caller's table gains score_z. The name and the tests say so.
add_z_score <- function(dt) {
  dt[, score_z := (score - mean(score)) / sd(score)]
  dt
}

summarise_by_group <- function(dt) {
  dt[, .(mean_val = mean(value)), by = group]
})---", "R/analysis.R")

# ── file: R/tidy.R ──────────────────────────────────────────────────────────────
dir.create("R", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# R/tidy.R
library(data.table)

# One row per term, for any fit whose summary() carries a coefficient matrix: lm, glm, lmer
tidy_coef <- function(fit) {
  co <- coef(summary(fit))
  data.table(term = rownames(co), estimate = co[, 1], se = co[, 2])
}

# One row per smooth term, from mgcv's summary()
tidy_smooth <- function(fit) {
  st <- summary(fit)$s.table
  data.table(term = rownames(st), edf = st[, "edf"], p = st[, "p-value"])
}

# One row per draw per variable, from anything posterior can read: a CmdStanMCMC's
# $draws(), a brmsfit's $fit, or a draws object. Never the fitting package's accessors
tidy_draws <- function(draws, variables) {
  d <- posterior::subset_draws(posterior::as_draws(draws), variable = variables)
  melt(as.data.table(posterior::as_draws_df(d)),
       id.vars = c(".chain", ".iteration", ".draw"), variable.name = "variable")
})---", "R/tidy.R")

# ── file: stan/normal.stan ──────────────────────────────────────────────────────
dir.create("stan", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(data {
  int<lower=0> N;
  vector[N] y;
}
parameters {
  real mu;
  real<lower=0> sigma;
}
model {
  mu ~ normal(0, 5);
  sigma ~ normal(0, 2);
  y ~ normal(mu, sigma);
})---", "stan/normal.stan")

# ── file: tests/test-tidy.R ─────────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-tidy.R
library(testthat)
library(data.table)
source(here::here("R", "tidy.R"))

test_that("tidy_coef returns one row per term with estimate and se", {
  fit <- lm(dist ~ speed, data = cars)
  out <- tidy_coef(fit)
  expect_s3_class(out, "data.table")
  expect_named(out, c("term", "estimate", "se"))
  expect_equal(out$term, c("(Intercept)", "speed"))
  expect_equal(out$estimate, unname(coef(fit)))
})

test_that("tidy_smooth reports the smooth's edf", {
  set.seed(1)
  d   <- data.frame(x = seq(0, 10, length.out = 100))
  d$y <- sin(d$x) + rnorm(100, sd = 0.2)
  out <- tidy_smooth(mgcv::gam(y ~ s(x), data = d))
  expect_equal(out$term, "s(x)")
  expect_gt(out$edf, 1)
})

test_that("tidy_draws gives one row per draw per variable", {
  ex  <- posterior::example_draws()     # eight schools: mu, tau, theta[1:8]
  out <- tidy_draws(ex, c("mu", "tau"))
  expect_named(out, c(".chain", ".iteration", ".draw", "variable", "value"))
  expect_equal(nrow(out), 2 * posterior::ndraws(ex))
  expect_equal(sort(unique(as.character(out$variable))), c("mu", "tau"))
}))---", "tests/test-tidy.R")

# ── file: tests/test-analysis.R ─────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-analysis.R
library(testthat)
# test_dir() runs with the working directory set to tests/, so source("R/analysis.R")
# does not resolve. here() finds the project root (a .git directory, an .Rproj file,
# or an empty .here file) from any working directory.
source(here::here("R", "analysis.R"))

# ── RED: write these before the function exists ───────────────────────────

test_that("compute_effect_size returns correct Cohen's d", {
  x <- c(2, 3, 5, 7, 8)
  y <- c(1, 2, 3, 4, 5)
  d <- compute_effect_size(x, y, type = "cohen_d")
  expect_type(d, "double")
  expect_length(d, 1)
  expect_gt(d, 0)                  # x has higher mean, so d should be positive
})

test_that("compute_effect_size errors on non-numeric input", {
  expect_error(compute_effect_size("a", 1:5), "must be numeric")
})

test_that("compute_effect_size handles equal vectors", {
  x <- c(1, 2, 3)
  expect_equal(compute_effect_size(x, x, type = "cohen_d"), 0)
}))---", "tests/test-analysis.R")

# ── file: tests/test-datatable.R ────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-datatable.R
library(testthat)
library(data.table)
source(here::here("R", "analysis.R"))

# ── Test that := does not affect the caller's object ──────────────────────
test_that("add_z_score does not modify input by reference", {
  dt <- data.table(score = c(1, 2, 3, 4, 5))
  original <- copy(dt)
  result <- add_z_score(copy(dt))       # pass a copy if function modifies in place
  expect_equal(dt, original)            # caller's dt unchanged
  expect_true("score_z" %in% names(result))
})

# ── Test groupwise correctness ─────────────────────────────────────────────
test_that("summarise_by_group returns correct means per group", {
  dt <- data.table(
    group = c("A", "A", "B", "B"),
    value = c(1, 3, 2, 4)
  )
  result <- summarise_by_group(dt)
  expect_equal(result[group == "A", mean_val], 2)
  expect_equal(result[group == "B", mean_val], 3)
}))---", "tests/test-datatable.R")

# ── file: tests/test-models.R ───────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-models.R
library(testthat)
library(data.table)
source(here::here("R", "analysis.R"))

# Good: tests the contract
test_that("fit_group_models returns one row per group per term", {
  dt <- data.table(
    group   = rep(c("A", "B"), each = 20),
    outcome = rnorm(40),
    age     = sample(18:65, 40, replace = TRUE)
  )
  result <- fit_group_models(dt, outcome ~ age, group_col = "group")
  expect_s3_class(result, "data.table")
  expect_true(all(c("term", "estimate") %in% names(result)))
  expect_equal(nrow(result), 2 * 2)   # 2 groups * 2 terms (intercept + age)
})

# Avoid: tests an implementation detail (the internal formula string))---", "tests/test-models.R")

# ── file: _targets.R ────────────────────────────────────────────────────────────
writeLines(r"---(# _targets.R
library(targets)

# Load your functions — keep them in R/ and source them here
tar_source("R/functions.R")

# Set options (packages available to all targets, common format, etc.)
tar_option_set(packages = c("data.table", "ggplot2"))

# Define the pipeline as a list of tar_target() calls
list(
  tar_target(raw_path,    "data/raw.csv", format = "file"),  # rerun if the file changes
  tar_target(raw_data,    load_raw(raw_path)),               # depends on raw_path
  tar_target(clean_data,  clean(raw_data)),                  # depends on raw_data
  tar_target(model,       fit_model(clean_data)),            # depends on clean_data
  tar_target(figure,      plot_results(model, clean_data))
))---", "_targets.R")

# ── file: R/functions.R ─────────────────────────────────────────────────────────
dir.create("R", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# R/functions.R
load_raw <- function(path) {
  fread(path)
}

clean <- function(dt) {
  dt <- copy(dt)
  dt <- dt[!is.na(outcome)]
  dt[, score_z := (score - mean(score)) / sd(score)]
  dt
}

fit_model <- function(dt) {
  lm(outcome ~ score_z + age + group, data = dt)
}

plot_results <- function(model, dt) {
  dt <- copy(dt)
  dt[, fitted := fitted(model)]
  ggplot(dt, aes(x = score_z, y = outcome, colour = group)) +
    geom_point() +
    geom_line(aes(y = fitted)) +
    theme_bw()
})---", "R/functions.R")

# ── file: data/raw.csv ──────────────────────────────────────────────────────────
dir.create("data", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(id,group,age,score,outcome
1,A,21,52,10.1
2,A,25,61,11.4
3,A,30,48,9.2
4,A,34,70,12.8
5,A,41,55,10.9
6,A,45,66,
7,B,22,58,9.8
8,B,27,63,10.7
9,B,31,45,8.9
10,B,36,72,12.1
11,B,40,50,9.5
12,B,44,68,11.6)---", "data/raw.csv")

# ── file: _targets_branching.R ──────────────────────────────────────────────────
writeLines(r"---(# _targets_branching.R
library(targets)
tar_source("R/functions.R")
tar_option_set(packages = "data.table")

# One function per branch. It carries the group label in its output, because the
# branch names targets generates are hashes, not labels.
tidy_group <- function(dt) {
  co <- coef(lm(outcome ~ score_z, data = dt))
  data.table(term = names(co), estimate = unname(co), group = dt$group[1])
}

list(
  tar_target(raw_path,   "data/raw.csv", format = "file"),
  tar_target(raw_data,   load_raw(raw_path)),
  tar_target(clean_data, clean(raw_data)),

  # Split into a list of data.tables — one per group. iteration = "list" makes
  # each branch below receive one element; with the default "vector" iteration
  # a branch gets a length-one list instead, and lm() fails with "object not found"
  tar_target(
    group_data,
    split(clean_data, by = "group"),
    iteration = "list"
  ),

  # One branch per group. iteration = "list" again, so the downstream target
  # receives the branches as a plain list rbindlist() can stack; with the default,
  # targets stacks them itself and rbindlist() refuses the result
  tar_target(
    group_coefs,
    tidy_group(group_data),
    pattern   = map(group_data),
    iteration = "list"
  ),

  # Aggregate: naming the upstream target gives a downstream target every branch.
  # tar_read() is for interactive use — never call it inside a command
  tar_target(all_coefs, rbindlist(group_coefs))
))---", "_targets_branching.R")

# ── file: _targets_grid.R ───────────────────────────────────────────────────────
writeLines(r"---(# _targets_grid.R: a specification grid, one branch per row
library(targets)
library(data.table)
tar_source("R/functions.R")
tar_option_set(
  packages   = "data.table",
  controller = crew::crew_controller_local(workers = 2),
  storage    = "worker",
  retrieval  = "worker"
)

# One specification in, one row out. The spec's own columns come along, so the result
# says which model it belongs to without a join
fit_spec <- function(dt, spec) {
  rhs <- if (spec$covariate == "none") "score_z" else paste("score_z", spec$covariate, sep = " + ")
  d   <- if (spec$subset == "all") dt else dt[group == spec$subset]
  fit <- lm(as.formula(paste("outcome ~", rhs)), data = d)
  data.table(spec, estimate = coef(fit)[["score_z"]], n = nrow(d))
}

list(
  tar_target(raw_path,   "data/raw.csv", format = "file"),
  tar_target(raw_data,   load_raw(raw_path)),
  tar_target(clean_data, clean(raw_data)),
  tar_target(spec,       CJ(covariate = c("none", "age"), subset = c("all", "A", "B"))),
  tar_target(spec_fit,   fit_spec(clean_data, spec), pattern = map(spec)),
  tar_target(curve,      spec_fit[order(estimate)])
))---", "_targets_grid.R")

# ── file: tests/test-functions.R ────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-functions.R — test the function, not the pipeline
library(testthat)
library(data.table)
source(here::here("R", "functions.R"))

test_that("clean removes NA rows and adds score_z", {
  dt <- data.table(outcome = c(1, NA, 3), score = c(10, 20, 30))
  result <- clean(dt)
  expect_equal(nrow(result), 2)
  expect_true("score_z" %in% names(result))
  expect_equal(result$score_z, scale(c(10, 30))[, 1])
}))---", "tests/test-functions.R")

# ── file: R/captions.R ──────────────────────────────────────────────────────────
dir.create("R", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# R/captions.R
# A caption states the finding, then the mechanics, in one sentence
caption_fit <- function(model, dt) {
  b <- coef(summary(model))["score_z", ]
  sprintf("Outcome rises %.2f per SD of score (SE %.2f, N = %d).",
          b[["Estimate"]], b[["Std. Error"]], nrow(dt))
})---", "R/captions.R")

# ── file: tests/test-captions.R ─────────────────────────────────────────────────
dir.create("tests", recursive = TRUE, showWarnings = FALSE)
writeLines(r"---(# tests/test-captions.R
library(testthat)
library(data.table)
source(here::here("R", "captions.R"))

test_that("caption_fit leads with the finding and ends with N", {
  dt  <- data.table(outcome = c(1, 2, 4, 5), score_z = c(-1.2, -0.4, 0.4, 1.2))
  cap <- caption_fit(lm(outcome ~ score_z, data = dt), dt)
  expect_match(cap, "^Outcome rises [0-9.]+ per SD of score")
  expect_match(cap, "N = 4\\)\\.$")
}))---", "tests/test-captions.R")

# ── file: report.qmd ────────────────────────────────────────────────────────────
writeLines(r"---(---
title: "Score and outcome"
format:
  html:
    lightbox: true
    embed-resources: true
---

```{r}
#| include: false
library(targets)
library(data.table)
source(here::here("R", "captions.R"))
tar_load(c(model, figure, clean_data))
```

The fit is read from the pipeline; nothing here refits it.

```{r}
#| echo: false
#| fig-cap: !expr caption_fit(model, clean_data)
figure
```)---", "report.qmd")

# ── file: _targets_report.R ─────────────────────────────────────────────────────
writeLines(r"---(# _targets_report.R: the minimal pipeline plus the report
library(targets)
library(tarchetypes)
tar_source("R/functions.R")
tar_option_set(packages = c("data.table", "ggplot2"))

list(
  tar_target(raw_path,    "data/raw.csv", format = "file"),
  tar_target(raw_data,    load_raw(raw_path)),
  tar_target(clean_data,  clean(raw_data)),
  tar_target(model,       fit_model(clean_data)),
  tar_target(figure,      plot_results(model, clean_data)),
  tar_quarto(report, "report.qmd")   # depends on whatever the document tar_load()s
))---", "_targets_report.R")

# ── On Pipes: Prefer Intermediate Variables ─────────────────────────────────────
library(data.table)

set.seed(1)
dt <- data.table(
  id    = 1:200,
  group = rep(c("A", "B"), 100),
  year  = rep(2021:2022, each = 100),
  score = c(rnorm(100, mean = 5), rnorm(100, mean = 6))
)
ref <- data.table(group = c("A", "B"), label = c("control", "treatment"))

# Prefer plain function calls over pipes
x      <- exp(pi)
result <- round(log(x), 3)

# Two-step pipe is acceptable, but the above is preferred
result <- log(x) |> round(3)

# More than two — use intermediate variables, not a chain
# Don't do this:
# result <- dt |> some_filter() |> some_agg() |> some_reshape() |> some_join(ref)

# Do this:
filtered   <- dt[!is.na(score)]
aggregated <- filtered[, .(mean_score = mean(score), n = .N), by = .(group, year)]
reshaped   <- dcast(aggregated, group ~ year, value.var = "mean_score")
result     <- merge(reshaped, ref, by = "group", all.x = TRUE)
result
stopifnot(nrow(result) == 2L)

# ── On Pipes: Prefer Intermediate Variables ─────────────────────────────────────
library(data.table)

set.seed(1)
dt <- data.table(
  id    = 1:200,
  group = rep(c("A", "B"), 100),
  score = c(rnorm(100, mean = 5), rnorm(100, mean = 6))
)

# When intermediate objects would be large, modify in place
dt[, score_z := (score - mean(score)) / sd(score)]
dt[, flag    := score_z > 2]
dt[, label   := fcase(flag & group == "A", "outlier_A",
                      flag & group == "B", "outlier_B",
                      default = "normal")]
dt

# ── The `[i, j, by]` Grammar ────────────────────────────────────────────────────
library(data.table)

set.seed(1)
dt <- data.table(
  id    = 1:100,
  age   = sample(15:45, 100, replace = TRUE),
  group = sample(c("A", "B"), 100, replace = TRUE),
  year  = sample(2020:2022, 100, replace = TRUE),
  score = rnorm(100, mean = 50, sd = 10)
)

# i: row filtering
dt[age > 30]
dt[group == "A" & !is.na(score)]

# j: column operations
dt[, .(mean_score = mean(score), n = .N)]
dt[, score_z := (score - mean(score)) / sd(score)]  # modify in place

# by: grouping
dt[, .(mean_score = mean(score)), by = group]
dt[, .(mean_score = mean(score)), by = .(group, year)]

# All three together
dt[age > 18, .(mean_score = mean(score), n = .N), by = group]

# ── Column Operations ───────────────────────────────────────────────────────────
library(data.table)

dt <- data.table(
  id    = 1:6,
  x     = c(1.2, 2.4, 3.1, 4.5, 5.0, 6.7),
  y     = c(10, 20, 30, 40, 50, 60),
  z     = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6),
  score = c(0.3, 0.7, 0.5, 0.9, 0.1, 0.8),
  group = c("A", "A", "B", "B", "A", "B")
)

# Add/modify columns in place
dt[, new_col := x * 2]
dt[, c("a", "b") := .(x + y, y - z)]

# Conditional assignment
dt[group == "A", flag := TRUE]
dt[, label := fifelse(score > 0.5, "high", "low")]  # fifelse is type-stable

# Delete a column
dt[, new_col := NULL]

# Apply a function to multiple columns by name
cols <- c("x", "y", "z")
dt[, (cols) := lapply(.SD, function(x) as.numeric(scale(x))), .SDcols = cols]
# as.numeric() drops the scaled:center / scaled:scale attributes scale() attaches
dt

# ── Grouping and Aggregation ────────────────────────────────────────────────────
library(data.table)

set.seed(42)
dt <- data.table(
  group      = rep(c("A", "B", "C"), each = 30),
  year       = rep(rep(2021:2023, each = 10), 3),
  value      = rnorm(90, mean = 100, sd = 15),
  score_math = rnorm(90, 70, 10),
  score_read = rnorm(90, 75, 8)
)

# Basic aggregation
summary_dt <- dt[, .(
  mean_val = mean(value, na.rm = TRUE),
  sd_val   = sd(value, na.rm = TRUE),
  n        = .N
), by = .(group, year)]
summary_dt
stopifnot(nrow(summary_dt) == 9L)

# Add group mean back to original table (no ungroup() needed)
dt[, group_mean := mean(value), by = group]

# Grouped operations on multiple columns
dt[, lapply(.SD, mean, na.rm = TRUE), by = group, .SDcols = c("score_math", "score_read")]

# .SD with column name patterns
dt[, lapply(.SD, function(x) x - mean(x)), .SDcols = patterns("^score")]

# ── Joins ───────────────────────────────────────────────────────────────────────
library(data.table)

dt_a <- data.table(
  id    = c("s01", "s02", "s03", "s04"),
  year  = c(2021, 2021, 2022, 2022),
  score = c(82, 74, 91, 68)
)
dt_b <- data.table(
  id    = c("s01", "s02", "s03", "s05"),
  group = c("ctrl", "treat", "ctrl", "treat")
)

# merge: inner, left, explicit names
merge(dt_a, dt_b, by = "id")                        # inner
merge(dt_a, dt_b, by = "id", all.x = TRUE)          # left join
merge(dt_a, dt_b, by.x = "id", by.y = "id")         # explicit names

# Keyed join (fast for large tables)
setkey(dt_a, id)
setkey(dt_b, id)
dt_b[dt_a]  # right join: all dt_a rows, matching dt_b

# Rolling join: last known price on or before each transaction
prices <- data.table(
  id    = c("X", "X", "X", "Y", "Y"),
  date  = as.IDate(c("2024-01-01", "2024-03-01", "2024-06-01",
                     "2024-01-01", "2024-04-01")),
  price = c(100, 105, 110, 200, 210)
)
transactions <- data.table(
  id   = c("X", "X", "Y"),
  date = as.IDate(c("2024-02-15", "2024-07-01", "2024-05-01"))
)
setkey(prices, id, date)
setkey(transactions, id, date)
prices[transactions, roll = TRUE]

stopifnot(nrow(merge(dt_a, dt_b, by = "id", all.x = TRUE)) == 4L,
          nrow(prices[transactions, roll = TRUE]) == 3L)

# ── Joins That Lose Rows ────────────────────────────────────────────────────────
library(data.table)

dt_a <- data.table(id = c("s01", "s02", "s03", "s04"), score = c(82, 74, 91, 68))
dt_b <- data.table(id = c("s01", "s02", "s03", "s05"), group = c("ctrl", "treat", "ctrl", "treat"))

# Say what the join must preserve, then check it
n_before <- nrow(dt_a)
joined   <- merge(dt_a, dt_b, by = "id", all.x = TRUE)
stopifnot(nrow(joined) == n_before)       # a left join keeps every left row...
stopifnot(!anyDuplicated(dt_b$id))        # ...only if the right side's key is unique

# What fell out, on each side: anti-joins
dt_a[!dt_b, on = "id"]   # in a, not in b: s04
dt_b[!dt_a, on = "id"]   # in b, not in a: s05

# A duplicated key multiplies rows silently. Check the key before, not the count after
dt_dup <- rbindlist(list(dt_b, dt_b[1]))
nrow(merge(dt_a, dt_dup, by = "id"))      # 4, not 3: s01 appears twice
stopifnot(nrow(merge(dt_a, dt_dup, by = "id")) == 4L)

# A key with two types does not join at all. data.table refuses, loudly
dt_int <- data.table(id = 1:3, x = 1:3)
dt_chr <- data.table(id = c("1", "2", "3"), y = 4:6)
msg <- tryCatch(merge(dt_int, dt_chr, by = "id"), error = conditionMessage)
msg
stopifnot(grepl("Incompatible join types", msg, fixed = TRUE))

# ── Reshaping ───────────────────────────────────────────────────────────────────
library(data.table)

# Wide to long
wide_dt <- data.table(
  id      = 1:4,
  year    = c(2021, 2021, 2022, 2022),
  score_1 = c(80, 75, 90, 85),
  score_2 = c(70, 65, 88, 82),
  score_3 = c(60, 72, 78, 91)
)

long_dt <- melt(
  wide_dt,
  id.vars       = c("id", "year"),
  measure.vars  = c("score_1", "score_2", "score_3"),
  variable.name = "wave",
  value.name    = "score"
)
long_dt

# Long back to wide
dcast(long_dt, id + year ~ wave, value.var = "score")

# Multiple value columns at once (add a weight column first)
long_dt[, weight := runif(.N, 0.5, 1.5)]
dcast(long_dt, id ~ wave, value.var = c("score", "weight"))
stopifnot(nrow(long_dt) == 12L, ncol(dcast(long_dt, id + year ~ wave, value.var = "score")) == 5L)

# ── Reference Semantics: Understand What You're Doing ───────────────────────────
library(data.table)

dt <- data.table(x = 1:3, y = c("a", "b", "c"))

# dt_shallow and dt point to the same object — modifying one changes both
dt_shallow <- dt
dt[, z := 99]
dt_shallow  # z column appears here too!

# copy() creates an independent object
dt2      <- data.table(x = 1:3, y = c("a", "b", "c"))
dt2_copy <- copy(dt2)
dt2[, z := 99]
dt2_copy  # z column does NOT appear

# Function that modifies in place — caller's object changes
add_flag <- function(d) {
  d[, flag := TRUE]
  invisible(d)
}
dt3 <- data.table(x = 1:3)
add_flag(dt3)
print(dt3)  # flag column is present

stopifnot("z" %in% names(dt_shallow), !"z" %in% names(dt2_copy), "flag" %in% names(dt3))

# ── Functional Programming with Base R ──────────────────────────────────────────
dt_list <- list(
  A = data.frame(score = c(80, 90, 70)),
  B = data.frame(score = c(60, 85, 75)),
  C = data.frame(score = c(95, 55, 88))
)

# lapply returns a list — reliable and explicit
means_list <- lapply(dt_list, function(d) mean(d$score))
means_list

# vapply: type-safe, returns named numeric vector
means_vec <- vapply(dt_list, function(d) mean(d$score), numeric(1))
means_vec

# Map over multiple inputs
list_a <- list(1:3, 4:6, 7:9)
list_b <- list(10, 20, 30)
Map(function(x, y) x + y, list_a, list_b)

# Reduce for accumulation
Reduce("+", list(1:4, 5:8, 9:12))
Reduce("+", list(1:4, 5:8, 9:12), accumulate = TRUE)

# ── Apply Over Data Frames / data.tables ────────────────────────────────────────
library(data.table)

mat <- matrix(c(1, 2, NA, 4, 5, 6, 7, NA, 9), nrow = 3)

colMeans(mat, na.rm = TRUE)
rowSums(mat, na.rm = TRUE)
apply(mat, 1, function(x) sum(x^2, na.rm = TRUE))  # row-wise
apply(mat, 2, max, na.rm = TRUE)                    # col-wise

# On a data.table
dt <- data.table(a = c(1, 2, 3), b = c(4, NA, 6), c = c(7, 8, 9))
dt[, lapply(.SD, mean, na.rm = TRUE), .SDcols = is.numeric]

# ── String Manipulation: stringr and stringi ────────────────────────────────────
library(stringr)

x    <- c("apple-42", "banana-7", "cherry-100", "NA-value", "café")
name <- "world"

# Detection
str_detect(x, "\\d+")
str_starts(x, "ban")
str_ends(x, "\\d")
str_count(x, "[aeiou]")

# Extraction
str_extract(x, "\\d+")            # first match
str_extract_all(x, "[a-z]+")      # all matches (returns list)
str_match(x, "(\\w+)-(\\d+)")     # capture groups → matrix

# Substitution
str_replace(x, "-", "_")          # first match
str_replace_all(x, "[aeiou]", "*") # all matches

# Splitting and combining
str_split(x, "-")
str_split_fixed(x, "-", n = 2)
str_c("item", 1:3, sep = "_")
str_glue("Hello {name}!")

# Basic operations
str_length(x)
str_to_lower(x)
str_trim("  spaces  ")
str_pad("42", width = 6, side = "left")
str_sub(x, 1, 5)
str_trunc(x, width = 8)

# Pattern helpers
str_detect(c("$100", "100"), fixed("$"))
str_detect(c("Abc123", "abc"), regex("ABC", ignore_case = TRUE))
str_detect(c("café", "cafe"), coll("é", locale = "fr"))

# ── String Manipulation: stringr and stringi ────────────────────────────────────
library(stringi)

x <- c("café", "naïve", "résumé", "hello")

stri_trans_general(x, "Latin-ASCII")       # strip accents: "cafe", "naive", ...
stri_sort(x, locale = "fr_FR")             # French locale sort
stri_pad_left(c("a", "bb", "ccc"), width = 5)
stri_count_regex(x, "[aeiou]")
stri_extract_all_words("the quick brown fox")

# ── Date/Time ───────────────────────────────────────────────────────────────────
Sys.Date()
as.Date("2024-01-15")
format(Sys.Date(), "%Y-%m")

start_date <- as.Date("2024-01-01")
end_date   <- as.Date("2024-06-30")
end_date - start_date
as.numeric(end_date - start_date)

seq(as.Date("2024-01-01"), as.Date("2024-06-01"), by = "month")

# ── ggplot2: It's Great, Use It ─────────────────────────────────────────────────
library(data.table)
library(ggplot2)

set.seed(7)
dt <- data.table(
  id        = 1:120,
  group     = rep(c("ctrl", "treat"), 60),
  condition = rep(c("low", "high", "low", "high"), 30),
  wave      = rep(1:3, each = 40),
  score     = rnorm(120, mean = 50, sd = 12),
  passed    = rbinom(120, 1, 0.65)
)
dt[, cohort := paste0("C", sample(1:3, 120, replace = TRUE))]

# ggplot2 works directly with data.tables
ggplot(dt, aes(x = group, y = score, fill = condition)) +
  geom_boxplot() +
  theme_bw()

# Compute summaries in data.table, then plot — don't pipe into ggplot
summary_dt <- dt[, .(
  mean = mean(score, na.rm = TRUE),
  se   = sd(score, na.rm = TRUE) / sqrt(.N)
), by = .(group, wave)]

ggplot(summary_dt, aes(x = wave, y = mean, color = group)) +
  geom_line() +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  theme_bw()

# ── Theme Preferences ───────────────────────────────────────────────────────────
library(ggplot2)

# Custom reusable theme layer
my_theme <- theme_bw(base_size = 12) +
  theme(
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey92"),
    legend.position  = "bottom"
  )

# ── Computed Variables ──────────────────────────────────────────────────────────
library(data.table)
library(ggplot2)

set.seed(7)
dt <- data.table(
  passed = rbinom(120, 1, 0.65),
  cohort = paste0("C", sample(1:3, 120, replace = TRUE))
)

my_theme <- theme_bw(base_size = 12) +
  theme(panel.grid.minor = element_blank(), legend.position = "bottom")

# Good: prepare, then plot
plot_dt <- dt[, .(
  n        = .N,
  pct_pass = mean(passed),
  ci_lo    = mean(passed) - 1.96 * sqrt(mean(passed) * (1 - mean(passed)) / .N),
  ci_hi    = mean(passed) + 1.96 * sqrt(mean(passed) * (1 - mean(passed)) / .N)
), by = cohort]

ggplot(plot_dt, aes(x = cohort, y = pct_pass, ymin = ci_lo, ymax = ci_hi)) +
  geom_pointrange() +
  my_theme

# ── Structure and Style ─────────────────────────────────────────────────────────
library(data.table)
source(here::here("R", "analysis.R"))

set.seed(1)
d <- compute_effect_size(rnorm(50, 5), rnorm(50, 4))
d
compute_effect_size(rnorm(50, 5), rnorm(50, 4), type = "glass_delta")

set.seed(2)
dt <- data.table(
  group     = rep(c("A", "B"), each = 50),
  outcome   = rnorm(100, 10, 2),
  predictor = rnorm(100, 5, 1)
)
coefs <- fit_group_models(dt, outcome ~ predictor, "group")
coefs
stopifnot(d > 0, nrow(coefs) == 4L, identical(names(coefs), c("group", "term", "estimate")))

# ── Avoid Growing Objects ───────────────────────────────────────────────────────
library(data.table)

n       <- 200
compute <- function(i) i^2 + rnorm(1)

# Bad: O(n²) copies
result_bad <- c()
for (i in seq_len(n)) result_bad <- c(result_bad, compute(i))

# Good: pre-allocate
result_good <- vector("numeric", n)
for (i in seq_len(n)) result_good[i] <- compute(i)

# Best for tabular results
results <- lapply(seq_len(n), function(i) data.table(i = i, val = compute(i)))
result  <- rbindlist(results)
result

# ── lapply + rbindlist: The Core Pattern ────────────────────────────────────────
library(data.table)
library(stringr)

# ── Core pattern ──────────────────────────────────────────────────────────

# Function returns one data.table per item; combine with rbindlist
summarise_group <- function(grp, dt) {
  d <- dt[group == grp]
  d[, .(group = grp, n = .N, mean_score = mean(score), sd_score = sd(score))]
}

set.seed(3)
dt     <- data.table(group = rep(c("A", "B", "C"), each = 40),
                     score = rnorm(120, 70, 10))
groups <- unique(dt$group)
rbindlist(lapply(groups, summarise_group, dt = dt))

# ── idcol: track which item produced each row ──────────────────────────────

fit_group <- function(group_dt) {
  co <- coef(lm(score ~ 1, data = group_dt))
  data.table(term = names(co), estimate = unname(co))
}
# Not as.data.table(co, keep.rownames = "term"): on a named vector that silently
# yields columns V1 and V2, and the "term" name is ignored.
dt_list <- split(dt, by = "group")
coefs   <- rbindlist(lapply(dt_list, fit_group), idcol = "group")
coefs
stopifnot(identical(names(coefs), c("group", "term", "estimate")))

# ── use.names: stack columns by name, not position ────────────────────────

r1 <- data.table(a = 1, b = 2)
r2 <- data.table(a = 3,      c = 5)
rbindlist(list(r1, r2), use.names = TRUE, fill = TRUE)

# ── Index-based: seed per simulation ──────────────────────────────────────

run_simulation <- function(sim_id) {
  set.seed(sim_id)
  x <- rnorm(30)
  data.table(sim_id = sim_id, estimate = mean(x), se = sd(x) / sqrt(length(x)))
}
sim_results <- rbindlist(lapply(seq_len(50), run_simulation))
sim_results
stopifnot(nrow(sim_results) == 50L)

# ── Composing with parallelism: swap lapply for mclapply ──────────────────
# The function is identical — only the mapping changes.
# Caveat: mclapply uses fork() and is unstable in RStudio/Positron on macOS.
# See the Parallelism section for details and the parLapply alternative.

# sim_results <- rbindlist(mclapply(seq_len(50), run_simulation, mc.cores = n_cores))

# ── Nested: lapply inside lapply, flatten with rbindlist ──────────────────

cohorts      <- c("C1", "C2")
outcome_vars <- c("score_a", "score_b")
set.seed(4)
dt2 <- data.table(
  cohort  = rep(cohorts, each = 20),
  score_a = rnorm(40),
  score_b = rnorm(40, mean = 1)
)
nested <- lapply(cohorts, function(coh) {
  sub <- dt2[cohort == coh]
  lapply(outcome_vars, function(v) {
    sub[, .(cohort = coh, outcome = v, estimate = mean(.SD[[v]], na.rm = TRUE))]
  })
})
rbindlist(unlist(nested, recursive = FALSE))

# ── Model Output as data.tables ─────────────────────────────────────────────────
library(data.table)
library(mgcv)
library(lme4)
source(here::here("R", "tidy.R"))

set.seed(5)
n  <- 200
dt <- data.table(group = rep(sprintf("g%02d", 1:10), each = 20), age = runif(n, 10, 20))
dt[, score   := 50 + 3 * sin(age / 3) + rnorm(n, sd = 2)]
dt[, outcome := 10 + 0.4 * score + rnorm(10)[as.integer(factor(group))] + rnorm(n)]

fits <- list(
  linear = lm(outcome ~ score, data = dt),
  mixed  = lmer(outcome ~ score + (1 | group), data = dt),
  smooth = gam(score ~ s(age), data = dt)
)
coefs <- rbindlist(lapply(fits[c("linear", "mixed")], tidy_coef), idcol = "model")
coefs
smooths <- tidy_smooth(fits$smooth)
smooths
stopifnot(identical(names(coefs), c("model", "term", "estimate", "se")), nrow(coefs) == 4L,
          smooths$term == "s(age)", smooths$edf > 1)

# ── Model Output as data.tables ─────────────────────────────────────────────────
library(data.table)
library(cmdstanr)
source(here::here("R", "tidy.R"))

set.seed(6)
y   <- rnorm(50, mean = 3, sd = 1.5)
mod <- cmdstan_model("stan/normal.stan")
fit <- mod$sample(data = list(N = length(y), y = y), chains = 2, iter_warmup = 300,
                  iter_sampling = 300, refresh = 0, seed = 6)

draws <- tidy_draws(fit$draws(), c("mu", "sigma"))
draws[, .(mean = mean(value), lo = quantile(value, 0.05), hi = quantile(value, 0.95)),
      by = variable]
stopifnot(identical(names(draws), c(".chain", ".iteration", ".draw", "variable", "value")),
          nrow(draws) == 2L * 600L,
          abs(draws[variable == "mu", mean(value)] - 3) < 0.6)

# ── Identifiers Are Character ───────────────────────────────────────────────────
library(data.table)
library(arrow)

csv <- tempfile(fileext = ".csv")
writeLines(c("id,score", "007,52", "042,61", "100,48"), csv)

fread(csv)$id                                     # 7 42 100: the zeros are gone
ids <- fread(csv, colClasses = c(id = "character"))
ids$id                                            # "007" "042" "100"

# The damage shows up two steps later, when the id has to match something else
paste0("sub-", fread(csv)$id)[1]                  # "sub-7": no such file, no such row
paste0("sub-", ids$id)[1]                         # "sub-007"

# Parquet keeps the type, so the decision made at the read survives every later read
pq <- tempfile(fileext = ".parquet")
write_parquet(ids, pq)
back <- as.data.table(read_parquet(pq))
stopifnot(is.character(back$id), identical(back$id, c("007", "042", "100")))

# ── Parallelism: Multicore vs Multiprocess ──────────────────────────────────────
library(data.table)
library(parallel)

n_cores <- max(1L, parallel::detectCores(logical = FALSE) - 1L)

run_simulation <- function(sim_id) {
  set.seed(sim_id)
  x <- rnorm(100)
  data.table(sim_id = sim_id, estimate = mean(x), se = sd(x) / sqrt(length(x)))
}

# ── Multicore (fork): mclapply ─────────────────────────────────────────────
# Use when: Unix/Mac, CPU-bound, workers share a large read-only object
# WARNING: unstable inside RStudio/Positron on macOS — run from terminal if hangs occur
# Reproducible because run_simulation() seeds itself from sim_id. mc.set.seed is TRUE by
# default and does not get you this — it seeds children from time and PID. Seed inside the
# worker, or set RNGkind("L'Ecuyer-CMRG") before set.seed().
sim_results <- rbindlist(mclapply(seq_len(50), run_simulation, mc.cores = n_cores))
sim_results

# ── Multiprocess (socket): parLapply ──────────────────────────────────────
# Use when: Windows, isolated workers needed, or distributing across nodes
cl <- makeCluster(n_cores)
# envir defaults to the global environment, which is not where run_simulation lives
# when this code runs inside a function or a sourced block
clusterExport(cl, varlist = "run_simulation", envir = environment())
invisible(clusterEvalQ(cl, library(data.table)))
# Not clusterSetRNGStream(cl, iseed = 42) here: it switches the workers to the
# L'Ecuyer-CMRG generator, and set.seed(sim_id) inside the worker then draws different
# numbers than the same call under the default generator. Use it when the worker does
# not seed itself; seeding in the worker and streams on the cluster do not combine.

sim_results2 <- rbindlist(parLapply(cl, seq_len(50), run_simulation))
stopCluster(cl)
sim_results2

# Both routes seed inside the worker from sim_id, so they agree exactly
stopifnot(identical(sim_results, sim_results2))

# Quick check before parallelising — is one item worth the overhead?
system.time(run_simulation(1))

# ── Binary Formats: Use Parquet ─────────────────────────────────────────────────
library(data.table)
library(arrow)

set.seed(7)
dt_raw <- data.table(
  id      = 1:1000,
  outcome = rnorm(1000),
  group   = sample(c("A", "B", "C"), 1000, replace = TRUE),
  date    = seq.Date(as.Date("2022-01-01"), by = "day", length.out = 1000)
)

# ── Parquet: the default for anything on disk ─────────────────────────────
parquet_path <- tempfile(fileext = ".parquet")
write_parquet(dt_raw, parquet_path)
dt <- as.data.table(read_parquet(parquet_path))

# Column selection on read — only the named columns leave the file
dt_sub <- as.data.table(read_parquet(parquet_path, col_select = c("id", "outcome")))
stopifnot(nrow(dt) == 1000L, identical(names(dt_sub), c("id", "outcome")))

# Compression is per-file; zstd is a good default when size matters
write_parquet(dt_raw, parquet_path, compression = "zstd")

# ── Format reference ───────────────────────────────────────────────────────
# parquet:  the default — compact, predicate pushdown, read by everything
# feather:  short-lived same-machine handoff only, written and consumed in one run
# RDS:      arbitrary R objects (models, lists) — not for data frames
# CSV:      only for handoff to tools that can't read binary formats

# ── Large Data: Arrow Datasets and DuckDB ───────────────────────────────────────
library(data.table)
library(arrow)
library(duckdb)

set.seed(8)
dt <- data.table(
  id      = 1:400,
  year    = rep(2020:2023, each = 100),
  group   = sample(c("control", "treatment"), 400, replace = TRUE),
  cohort  = sample(c("C1", "C2"), 400, replace = TRUE),
  outcome = rnorm(400, 10, 2),
  weight  = runif(400)
)

# ── Partition on write ────────────────────────────────────────────────────
part_dir <- file.path(tempdir(), "partitioned")
write_dataset(dt, path = part_dir, format = "parquet",
              partitioning = c("year", "group"))

# ── DuckDB ────────────────────────────────────────────────────────────────
# SQL is the query language here — no dplyr verbs needed or loaded
con <- dbConnect(duckdb())
duckdb_register(con, "dt", dt)

# WHERE = filter rows, SELECT = columns, GROUP BY = aggregate
result_dt <- as.data.table(dbGetQuery(con, "
  SELECT   cohort,
           AVG(outcome)  AS mean_outcome,
           COUNT(*)      AS n
  FROM     dt
  WHERE    year = 2021
    AND    \"group\" = 'treatment'
  GROUP BY cohort
"))
result_dt

# Window functions
result_ranked <- as.data.table(dbGetQuery(con, "
  SELECT   id, cohort, outcome,
           ROW_NUMBER() OVER (PARTITION BY cohort ORDER BY outcome DESC) AS rnk
  FROM     dt
  WHERE    year >= 2021
"))
result_ranked

# Query partitioned parquet files directly — nothing loaded into R first
result_parquet <- as.data.table(dbGetQuery(con, sprintf("
  SELECT   cohort, AVG(outcome) AS mean_outcome, COUNT(*) AS n
  FROM     read_parquet('%s/**/*.parquet')
  WHERE    year = 2021
    AND    \"group\" = 'treatment'
  GROUP BY cohort
", part_dir)))
result_parquet

# The in-memory table and the partitioned files answer the same query the same way.
# all.equal(), not identical(): the files are summed in a different order, and floating
# point addition is not associative
stopifnot(isTRUE(all.equal(result_dt[order(cohort)], result_parquet[order(cohort)])))

dbDisconnect(con, shutdown = TRUE)

# ── Memory Monitoring ───────────────────────────────────────────────────────────
library(data.table)

dt    <- data.table(x = rnorm(1e5), y = rnorm(1e5))
small <- data.table(a = 1:10)

format(object.size(dt), units = "MB")

tables()  # accurate sizes for all data.tables in session

sizes <- vapply(ls(), function(nm) object.size(get(nm)), numeric(1))
head(sort(sizes, decreasing = TRUE), 5)

rm(small)
gc()

# ── Vectorization ───────────────────────────────────────────────────────────────
library(data.table)

set.seed(9)
dt <- data.table(
  x         = rnorm(1000),
  y         = rnorm(1000, 5),
  score     = runif(1000),
  threshold = 0.5
)

# Bad: element-wise loop
result_loop <- numeric(nrow(dt))
for (i in seq_len(nrow(dt))) result_loop[i] <- dt$x[i] * 2 + dt$y[i]

# Good: vectorized
dt[, result := x * 2 + y]

# fcase: fast multi-condition assignment (data.table's case_when)
dt[, category := fcase(
  score > 0.8, "high",
  score > 0.5, "medium",
  default = "low"
)]

# fifelse: fast type-stable ifelse
dt[, verdict := fifelse(score > threshold, "pass", "fail")]
dt
stopifnot(all(dt$verdict %in% c("pass", "fail")), all(dt$category %in% c("high", "medium", "low")))

# ── S3: Default for Most Work ───────────────────────────────────────────────────
new_model_result <- function(coefs, vcov_mat, df, call) {
  obj <- list(coefs = coefs, vcov = vcov_mat, df = df, call = call)
  class(obj) <- "model_result"
  obj
}

print.model_result <- function(x, ...) {
  cat("Model Result\n")
  cat("Call:", deparse(x$call), "\n\n")
  print(x$coefs)
  invisible(x)
}

coef.model_result <- function(object, ...) object$coefs

# Demonstrate
set.seed(10)
fit <- lm(dist ~ speed, data = cars)
res <- new_model_result(
  coefs    = coef(fit),
  vcov_mat = vcov(fit),
  df       = df.residual(fit),
  call     = fit$call
)
print(res)
coef(res)

# ── S4: For Bioconductor or Complex Dispatch ────────────────────────────────────
library(data.table)

setClass("Participant", representation(
  id    = "character",
  waves = "data.table",
  meta  = "list"
))

setGeneric("n_waves", function(x) standardGeneric("n_waves"))
setMethod("n_waves", "Participant", function(x) nrow(x@waves))

p <- new("Participant",
         id    = "s001",
         waves = data.table(wave = 1:3, score = c(80, 85, 90)),
         meta  = list(site = "Lab A"))
n_waves(p)

# ── S7: Learn It, Default to S3 ─────────────────────────────────────────────────
library(S7)

Interval <- new_class("Interval",
  properties = list(
    lo = class_double,
    hi = class_double
  ),
  validator = function(self) {
    if (self@hi < self@lo) "@hi must be >= @lo"
  }
)

x <- Interval(lo = 0, hi = 1)
x@lo
x@hi

# Validator fires on invalid input
msg <- tryCatch(Interval(lo = 5, hi = 1), error = function(e) conditionMessage(e))
msg
stopifnot(grepl("@hi must be >= @lo", msg, fixed = TRUE))

# ── 1. Profile First ────────────────────────────────────────────────────────────
library(data.table)

set.seed(11)
dt <- data.table(
  x     = rnorm(1e5),
  group = sample(letters[1:5], 1e5, replace = TRUE)
)

# system.time for a quick check
system.time(dt[, .(mean_x = mean(x)), by = group])

# library(profvis)
# profvis(dt[, .(mean_x = mean(x)), by = group])

# ── 2. Benchmark Alternatives ───────────────────────────────────────────────────
library(data.table)
library(bench)

set.seed(11)
dt <- data.table(
  x     = rnorm(1e5),
  group = sample(letters[1:5], 1e5, replace = TRUE)
)

bench::mark(
  data_table  = dt[, .(mean_x = mean(x)), by = group],
  base_tapply = tapply(dt$x, dt$group, mean),
  min_iterations = 20,
  check = FALSE
)

# ── 3. Common Bottlenecks and Fixes ─────────────────────────────────────────────
# Bottleneck: string operations in a loop
# Fix: vectorize with str_detect/str_replace_all (stringr) or base gsub/grep

# Bottleneck: row-by-row data frame modification
# Fix: data.table := assignment

# Bottleneck: repeated subsetting without index
# Fix: setkey() + keyed joins

# Bottleneck: reading same large file multiple times
# Fix: read once, write parquet; see the Large Data section

# ── Dependency Philosophy ───────────────────────────────────────────────────────
# - data.table: reference semantics and a grouping grammar base R lacks; no dependencies
# - ggplot2:    a grammar of graphics base graphics does not have, and it stands alone
# - stringr:    one consistent string API; a thin layer over stringi
# - stringi:    ICU-backed Unicode and locale operations base R cannot do
# - arrow:      parquet, a cross-language on-disk format, and lazy datasets
# - duckdb:     out-of-core SQL over parquet, zero-copy with arrow
# - here:       project-root paths that survive test_dir() changing the working directory
# - lubridate:  date arithmetic base R makes error-prone; heavy date work only
# - S7:         validated, typed classes; experimental, so justified per class
# - testthat:   the test runner
# - targets:    the dependency graph for a multi-step analysis
# - tarchetypes: tar_quarto(), so the report is a target and cannot go stale
# - quarto:     renders the report from R; the Quarto CLI does the work
# - crew:       where targets run; the same pipeline on a laptop, a scheduler, or a cloud
# - parallel:   ships with R
# - Rcpp:       C++ once profiling has shown R is the bottleneck
# - Matrix:     sparse matrices
# - lme4/brms:  modeling
# - cmdstanr:   the Stan backend; posterior reads its draws
# - posterior:  draws and summaries from any Bayesian fit, independent of the backend

# Not worth adding to avoid writing 3 lines of base R:
# - dplyr   (use data.table)
# - purrr   (use lapply/vapply/Map)
# - tidyr   (use melt/dcast from data.table)
# - forcats (use factor() / levels())
# - readr   (use fread)
# - tibble  (use data.table or data.frame)
# - fst     (use parquet)
# - tidyverse (meta-package — pulls in everything; prefer individual tools)

# ── Input Validation ────────────────────────────────────────────────────────────
library(data.table)

fit_model <- function(dt, outcome, predictors, max_iter = 100) {
  if (!is.data.table(dt))
    stop("`dt` must be a data.table")
  if (!is.character(outcome) || length(outcome) != 1)
    stop("`outcome` must be a single string")
  missing_cols <- setdiff(c(outcome, predictors), names(dt))
  if (length(missing_cols) > 0)
    stop("Columns not found in `dt`: ", paste(missing_cols, collapse = ", "))
  if (!is.numeric(max_iter) || max_iter < 1)
    stop("`max_iter` must be a positive integer")
  lm(as.formula(paste(outcome, "~", paste(predictors, collapse = "+"))), data = dt)
}

dt <- data.table(y = rnorm(50), x1 = rnorm(50), x2 = rnorm(50))
fit_model(dt, "y", c("x1", "x2"))

# Validation fires correctly
msg_col <- tryCatch(fit_model(dt, "y", c("x1", "missing_col")), error = conditionMessage)
msg_cls <- tryCatch(fit_model(as.data.frame(dt), "y", "x1"),    error = conditionMessage)
msg_col
msg_cls
stopifnot(grepl("missing_col", msg_col, fixed = TRUE), grepl("must be a data.table", msg_cls, fixed = TRUE))

# warning() for recoverable issues
dt_with_na <- copy(dt)
dt_with_na[c(3, 7, 12), y := NA]

if (any(is.na(dt_with_na$y))) {
  warning(sum(is.na(dt_with_na$y)),
          " NA values in `y` will be removed.")
}

# ── Running Tests ───────────────────────────────────────────────────────────────
# Run all tests in a directory
testthat::test_dir("tests/")

# Run a single file
testthat::test_file("tests/test-analysis.R")

# In a package: devtools::test()

# Run a subset of files: filter is a regex on the file name with "test-" and ".R"
# stripped — not on test descriptions. This runs tests/test-analysis.R only
testthat::test_dir("tests/", filter = "analysis")

# ── A Minimal Pipeline ──────────────────────────────────────────────────────────
library(targets)

# Run the pipeline — only outdated targets execute
tar_make()

# Inspect results
tar_read(clean_data)    # load a target's value into session
tar_load(model)         # load into environment by name

# Check pipeline status
tar_outdated()          # which targets need to rerun; nothing, right after tar_make()
tar_manifest()          # table of all targets and their commands
# tar_visnetwork()      # dependency graph in the Viewer; needs the visNetwork package

stopifnot(length(tar_outdated()) == 0L, inherits(model, "lm"), nrow(tar_read(clean_data)) == 11L)

# ── Branching: Map Over Many Inputs ─────────────────────────────────────────────
library(targets)
tar_make(script = "_targets_branching.R", store = "_targets_branching")
all_coefs <- tar_read(all_coefs, store = "_targets_branching")
all_coefs
stopifnot(identical(names(all_coefs), c("term", "estimate", "group")),
          identical(sort(unique(all_coefs$group)), c("A", "B")))

# ── Branching: Map Over Many Inputs ─────────────────────────────────────────────
library(targets)
tar_make(script = "_targets_grid.R", store = "_targets_grid")
curve <- tar_read(curve, store = "_targets_grid")
curve
stopifnot(nrow(curve) == 6L, identical(names(curve), c("covariate", "subset", "estimate", "n")))

# ── Reports: Quarto on Top of targets ───────────────────────────────────────────
library(targets)
tar_make(script = "_targets_report.R")
progress <- tar_progress()
progress
stopifnot(file.exists("report.html"),
          progress$progress[progress$name == "model"]  == "skipped",
          progress$progress[progress$name == "report"] == "completed")
html <- paste(readLines("report.html", warn = FALSE), collapse = "\n")
stopifnot(grepl("Outcome rises", html, fixed = TRUE), grepl("lightbox", html, fixed = TRUE))

